#ifndef _BRESEQ_ERROR_COUNT_H_
#define _BRESEQ_ERROR_COUNT_H_

#include <string>
#include <vector>

namespace breseq {
	
	/*! Calculate errors in the given BAM file based on reference FAI files.
	 
	 \param bam is the read file generated by breseq.
	 \param fastas is the list of FASTA files that correspond to the reference sequences; generates FAI files as needed.
	 \param output_dir is the directory in which output files will be placed.
	 \param coverage_suffix is the suffix of the coverage distribution filename; will be prepended with the read sequence name.
	 \param error_suffix is the suffix of the error counts filename; will be prepended with the FAI filename.
	 */
	void error_count(const std::string& bam, 
									 const std::vector<std::string>& fastas,
									 const std::string& output_dir,
									 const std::string& coverage_suffix,
									 const std::string& error_suffix);
	
} // breseq

#endif
