#=GENOME_DIFF	1.0
#=CREATED	12:07:46 18 Jun 2026
#=PROGRAM	breseq 0.40.1
#=COMMAND	./src/c/breseq/breseq -j 4 -o /Users/jbarrick/src/breseq/.claude/worktrees/soft-clipping-evidence/tests/tmv_plasmid_circular_deletion_end_only -r /Users/jbarrick/src/breseq/.claude/worktrees/soft-clipping-evidence/tests/tmv_plasmid_circular_deletion_end_only/../data/tmv_plasmid/tmv-plasmid-truncate-start.gbk /Users/jbarrick/src/breseq/.claude/worktrees/soft-clipping-evidence/tests/tmv_plasmid_circular_deletion_end_only/../data/tmv_plasmid/D3-9_1P.fastq.gz /Users/jbarrick/src/breseq/.claude/worktrees/soft-clipping-evidence/tests/tmv_plasmid_circular_deletion_end_only/../data/tmv_plasmid/D3-9_2P.fastq.gz
#=REFSEQ	/Users/jbarrick/src/breseq/.claude/worktrees/soft-clipping-evidence/tests/tmv_plasmid_circular_deletion_end_only/../data/tmv_plasmid/tmv-plasmid-truncate-start.gbk
#=READSEQ	/Users/jbarrick/src/breseq/.claude/worktrees/soft-clipping-evidence/tests/tmv_plasmid_circular_deletion_end_only/../data/tmv_plasmid/D3-9_1P.fastq.gz
#=READSEQ	/Users/jbarrick/src/breseq/.claude/worktrees/soft-clipping-evidence/tests/tmv_plasmid_circular_deletion_end_only/../data/tmv_plasmid/D3-9_2P.fastq.gz
#=CONVERTED-BASES	2735772
#=CONVERTED-READS	18371
#=INPUT-BASES	2738037
#=INPUT-READS	18386
#=MAPPED-BASES	2375419
#=MAPPED-READS	16340
DEL	1	2,3	TMV-plasmid-truncate-start	3068	207	gene_name=–/–	gene_position=intergenic (–/–)	gene_product=–/–	gene_strand=–/–	locus_tag=–/–	mutation_category=large_deletion	position_end=3274	position_start=3068	ref_seq=207-bp
MC	2	.	TMV-plasmid-truncate-start	3068	3274	0	0	gene_name=–/–	gene_position=intergenic (–/–)	gene_product=–/–	gene_strand=–/–	left_inside_cov=86	left_outside_cov=878	locus_tag=–/–	right_inside_cov=1	right_outside_cov=NA
JC	3	.	TMV-plasmid-truncate-start	1	1	TMV-plasmid-truncate-start	3067	-1	0	alignment_overlap=9	coverage_minus=396	coverage_plus=378	flanking_left=151	flanking_right=151	frequency=1	junction_possible_overlap_registers=138	key=TMV-plasmid-truncate-start__1__1__TMV-plasmid-truncate-start__3076__-1__9____151__151__0__0	max_left=141	max_left_minus=141	max_left_plus=141	max_min_left=69	max_min_left_minus=69	max_min_left_plus=69	max_min_right=71	max_min_right_minus=71	max_min_right_plus=71	max_pos_hash_score=278	max_right=141	max_right_minus=141	max_right_plus=141	neg_log10_pos_hash_p_value=0.0	new_junction_coverage=1.13	new_junction_read_count=788	polymorphism_frequency=9.765e-01	pos_hash_score=204	prediction=consensus	side_1_annotate_key=gene	side_1_continuation=0	side_1_coverage=0.00	side_1_gene_name=–/–	side_1_gene_position=intergenic (–/–)	side_1_gene_product=–/–	side_1_gene_strand=–/–	side_1_locus_tag=–/–	side_1_overlap=9	side_1_possible_overlap_registers=147	side_1_read_count=0	side_1_redundant=0	side_2_annotate_key=gene	side_2_continuation=0	side_2_coverage=0.05	side_2_gene_name=–/–	side_2_gene_position=intergenic (–/–)	side_2_gene_product=–/–	side_2_gene_strand=–/–	side_2_locus_tag=–/–	side_2_overlap=0	side_2_possible_overlap_registers=138	side_2_read_count=38	side_2_redundant=0	total_non_overlap_reads=774
JC	4	.	TMV-plasmid-truncate-start	359	1	TMV-plasmid-truncate-start	652	-1	0	alignment_overlap=0	coverage_minus=7	coverage_plus=7	flanking_left=151	flanking_right=151	frequency=1.512e-02	junction_possible_overlap_registers=147	key=TMV-plasmid-truncate-start__359__1__TMV-plasmid-truncate-start__652__-1__0____151__151__0__0	max_left=144	max_left_minus=144	max_left_plus=118	max_min_left=6	max_min_left_minus=3	max_min_left_plus=6	max_min_right=70	max_min_right_minus=70	max_min_right_plus=67	max_pos_hash_score=296	max_right=150	max_right_minus=149	max_right_plus=150	neg_log10_pos_hash_p_value=18.0	new_junction_coverage=0.02	new_junction_read_count=14	polymorphism_frequency=1.512e-02	pos_hash_score=9	prediction=polymorphism	reject=COVERAGE_EVENNESS_SKEW,FREQUENCY_CUTOFF	side_1_annotate_key=gene	side_1_continuation=0	side_1_coverage=1.26	side_1_gene_name=–/–	side_1_gene_position=intergenic (–/–)	side_1_gene_product=–/–	side_1_gene_strand=–/–	side_1_locus_tag=–/–	side_1_overlap=0	side_1_possible_overlap_registers=147	side_1_read_count=936	side_1_redundant=0	side_2_annotate_key=gene	side_2_continuation=0	side_2_coverage=1.20	side_2_gene_name=–/–	side_2_gene_position=intergenic (–/–)	side_2_gene_product=–/–	side_2_gene_strand=–/–	side_2_locus_tag=–/–	side_2_overlap=0	side_2_possible_overlap_registers=147	side_2_read_count=888	side_2_redundant=0	total_non_overlap_reads=14
JC	5	.	TMV-plasmid-truncate-start	2306	1	TMV-plasmid-truncate-start	2382	1	0	alignment_overlap=8	coverage_minus=1	coverage_plus=4	flanking_left=151	flanking_right=151	frequency=6.477e-03	junction_possible_overlap_registers=139	key=TMV-plasmid-truncate-start__2306__1__TMV-plasmid-truncate-start__2374__1__8____151__151__0__0	max_left=83	max_left_minus=71	max_left_plus=83	max_min_left=71	max_min_left_minus=71	max_min_left_plus=61	max_min_right=56	max_min_right_minus=0	max_min_right_plus=56	max_pos_hash_score=280	max_right=140	max_right_minus=72	max_right_plus=140	neg_log10_pos_hash_p_value=19.7	new_junction_coverage=0.01	new_junction_read_count=6	polymorphism_frequency=6.477e-03	pos_hash_score=5	prediction=polymorphism	reject=COVERAGE_EVENNESS_SKEW,FREQUENCY_CUTOFF	side_1_annotate_key=gene	side_1_continuation=0	side_1_coverage=1.27	side_1_gene_name=–/–	side_1_gene_position=intergenic (–/–)	side_1_gene_product=–/–	side_1_gene_strand=–/–	side_1_locus_tag=–/–	side_1_overlap=8	side_1_possible_overlap_registers=147	side_1_read_count=943	side_1_redundant=0	side_2_annotate_key=gene	side_2_continuation=0	side_2_coverage=1.36	side_2_gene_name=–/–	side_2_gene_position=intergenic (–/–)	side_2_gene_product=–/–	side_2_gene_strand=–/–	side_2_locus_tag=–/–	side_2_overlap=0	side_2_possible_overlap_registers=139	side_2_read_count=949	side_2_redundant=0	total_non_overlap_reads=5
UN	6	.	TMV-plasmid-truncate-start	3116	3274
SC	7	.	TMV-plasmid-truncate-start	570	-1	log10_e_value=2.3	read_count=11	total_count=26
SC	8	.	TMV-plasmid-truncate-start	1942	-1	log10_e_value=3.8	read_count=9	total_count=13
SC	9	.	TMV-plasmid-truncate-start	2508	1	log10_e_value=2.4	read_count=8	total_count=13
SC	10	.	TMV-plasmid-truncate-start	3116	1	log10_e_value=13.8	read_count=18	total_count=21
