---
abstract: 'genome diff tools for anaylzing mutations'
author:
  - 'Jeffrey E. Barrick <jeffrey.e.barrick@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GenomeDiff
provides:
  GenomeDiff:
    file: lib/GenomeDiff.pm
    version: 1.00
  GenomeDiff::BaseSubstitutionFile:
    file: lib/GenomeDiff/BaseSubstitutionFile.pm
    version: 0
  GenomeDiff::Output:
    file: lib/GenomeDiff/Output.pm
    version: 0
  GenomeDiff::PreterminationTables:
    file: lib/GenomeDiff/PreterminationTables.pm
    version: 0
  GenomeDiff::ReferenceSequence:
    file: lib/GenomeDiff/ReferenceSequence.pm
    version: 0
  GenomeDiff::SynonymousNonsynonymous:
    file: lib/GenomeDiff/SynonymousNonsynonymous.pm
    version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.00
