---
abstract: 'genome diff tools for anaylzing mutations'
author:
  - 'Jeffrey E. Barrick <jeffrey.e.barrick@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GenomeDiff
provides:
  GenomeDiff:
    file: lib/GenomeDiff.pm
    version: '1.00'
  GenomeDiff::BaseSubstitutionFile:
    file: lib/GenomeDiff/BaseSubstitutionFile.pm
  GenomeDiff::Output:
    file: lib/GenomeDiff/Output.pm
  GenomeDiff::PreterminationTables:
    file: lib/GenomeDiff/PreterminationTables.pm
  GenomeDiff::ReferenceSequence:
    file: lib/GenomeDiff/ReferenceSequence.pm
  GenomeDiff::SynonymousNonsynonymous:
    file: lib/GenomeDiff/SynonymousNonsynonymous.pm
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '1.00'
